### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Zelzahn** [SELab-2/OSOC-5#142]
There is already a password reset endpoint provided by dj-auth, but I presume this isn't working. There are probably some configurations missing.

**Comment by Wouter01** [comment]
Can this be closed?

**Comment by Zelzahn** [comment]
@sheemeryck Since you worked on password reset, registration etc., what is your opinion?

**Comment by sheemeryck** [comment]
Sorry, again no notification, and I don't think so, it's still needed but it can't be implemented untill emails can be send.
