### ISSUE TITLE
CSRF issue on production server

### ISSUE THREAD

**Issue by Wouter01** [SELab-2/OSOC-5#195]
There seem to still be some leftovers of CSRF on the production server.
Steps to produce the error:
1. Open private tab of clear cookies 
2. [Login](https://sel2-5.ugent.be/login) -> Success
3. [Login](https://sel2-5.ugent.be/login) again -> Fail

**Comment by Wouter01** [comment]
The sessionid seems to be causing the issue here. If the cookie is deleted after being logged in on the production server, everything works normally. If I'm right the sessionid is generated and sent by the middleware `django.contrib.sessions.middleware.SessionMiddleware`. Unfortunately, this is used by the adminpanel and this can't be just deleted. @henricattoire, do you know how to solve this? We could just delete the cookie in the frontend, but that doesn't seem a clean option. I also heard you might have found another workaround by adding CSRF cookies back?

**Comment by henricattoire** [comment]
This isssue was solved by adding `CsrfMiddleware` in the Django (backend) and adding the `X-CSRFToken` with every request in Vue (frontend).
