### ISSUE TITLE
Make coach view

### ISSUE THREAD

**Issue by lisadejonghe** [SELab-2/OSOC-5#283]
Currently everything is made for a admin. We should make sure coaches don't see things they should not see, like they should not be able to make a decision.

- Making a final decision
- Viewing the "Manage Users" tab
- Viewing the "Mails" tab

**Comment by Zelzahn** [comment]
Admin only actions:
- Making a final decision
- Viewing the "Manage Users" tab

Did I forget any actions?

**Comment by lisadejonghe** [comment]
Coaches also cannot see the "Mails" tab. I think that's all?

**Comment by Wouter01** [comment]
A coach is also not allowed to assign a student to a project. I'll fix this asap

**Comment by lisadejonghe** [comment]
A coach is allowed to assign a student to a project, no?

**Comment by Zelzahn** [comment]
I'll ask this question to the other groups. Curious if they allow it or not.
