### ISSUE TITLE
Create projects page

### ISSUE THREAD

**Issue by lisadejonghe** [SELab-2/OSOC-5#290]
- [x] Remove filled in data when having submitted a new project
- [x] Rename `Role` to `Skill`
- [x] Maybe add a information sign (like with comments that coaches add to their suggestion) instead of giving a full column to the comment for a skill
- [x] Get paginated results for `Skills` 
- [x] Get paginated results for `Coaches`
- [x] Remove the obligatory `http://` or `https://`
- [x] Change layout of `Add Role` popup to have only Quasar colors
- [x] When skill failed to delete have negative callback
- [x] Fix search for `Skills`

**Comment by lasaeren** [comment]
for progress check #316
