### ISSUE TITLE
Filtering on suggestion/decision

### ISSUE THREAD

**Issue by lisadejonghe** [SELab-2/OSOC-5#291]
Is it best to be able to filter on a suggestion or a decision (or maybe both, which would make the list of filters even longer and I don't know what to do if it is to long on a small, maybe 13 inch, screen?).

**Comment by Zelzahn** [comment]
I think that filtering on a suggestion is sufficient, no?

**Comment by lisadejonghe** [comment]
Maybe that is indeed enough. I don't really see indeed why filtering on a decision would be necessary. This should be changed in de backend I think, because now, it filters on the decision.

**Comment by leveys** [comment]
how would you filter on suggestions?
for example, if i filter on suggestion=yes, which students should be returned?
- all students that have at least 1 'yes' suggestion
- all students that have a majority of 'yes' suggestions
- all students that you have suggested 'yes'

**Comment by lisadejonghe** [comment]
I think yes would mean that you, yourself, suggested yes on that student?

**Comment by leveys** [comment]
maybe this would be a good question for the client, since they will be using the tool

**Comment by leveys** [comment]
https://github.com/SELab-2/OSOC-opgave/discussions/54
