### ISSUE TITLE
question about apps.py

### ISSUE THREAD

**Issue by leveys** [SELab-2/OSOC-5#294]
a question about apps.py for @Zelzahn;
in the CommonConfig class there is an import that is unused, is this necessary?
Pylint gives an error for this import so either this import must be removed, or the pylint action must be changed such that it doesnt error on this file.

**Comment by Zelzahn** [comment]
This import is needed because it loads the signals. I see that you already added the pylint disable on `be/pylint-fixes` so this issue can be closed.
