### ISSUE TITLE
add options to pylint

### ISSUE THREAD

**Issue by leveys** [SELab-2/OSOC-5#297]
i think some pylint errors are unnecessary and should be removed from the pylint action:

- [x] Unused argument 'pk' (unused-argument)
- [x] Too many ancestors (9/7) (too-many-ancestors)
- [x] Method could be a function (no-self-use)
- [x] Argument name "pk" doesn't conform to snake_case naming style (invalid-name)
- [x] Variadics removed in overridden 'SkillViewSet.destroy' method (arguments-differ)
- [x] Trailing whitespace (trailing-whitespace)
- [x] Wildcard import common (wildcard-import)
- [x] Method 'create' is abstract in class 'BaseSerializer' but is not overridden (abstract-method)

**Comment by henricattoire** [comment]
I will look at it. Can I add changes to #296 or do I need to create a seperate pr?

**Comment by leveys** [comment]
yes you can add this to #296, i dont think it will cause too much problems

**Comment by henricattoire** [comment]
It is also possible to [suppress warnings](https://pylint.pycqa.org/en/latest/faq.html#is-it-possible-to-locally-disable-a-particular-message) locally instead of completely disabling them.

```
class CustomLoginSerializer(LoginSerializer): # pylint: disable=abstract-method
```

I don't know what you think about this?

**Comment by leveys** [comment]
that's a good idea, i think it's indeed better to disable some warnings locally instead of globally
