### ISSUE TITLE
which backend tests are necessary?

### ISSUE THREAD

**Issue by leveys** [SELab-2/OSOC-5#298]
there are a few files in the backend that are currently not tested, can/should these files be tested?

- [ ] ~~adapters.py~~
- [ ] consumers.py
- [ ] forms.py
- [x] signals.py
- [ ] routing.py
- [ ] apps.py
- [x] serializers.py (CustomLoginSerializer and CustomRegisterSerializer)

**Comment by Zelzahn** [comment]
Signals.py could be checked by creating a new coach and checking if the `is_active` field is false, but I doubt this would count for the coverage. Routing and consumers could be tested in theory ([documentation](https://channels.readthedocs.io/en/stable/topics/testing.html)).

**Comment by leveys** [comment]
login and register serializers and views are tested
we will not be writing tests for consumers, forms, routing and apps, as this will take up too much time and we think this is not necessary
