### ISSUE TITLE
removing own account doesn't work as intended

### ISSUE THREAD

**Issue by sheemeryck** [SELab-2/OSOC-5#314]
If you remove yourself (logged in user), you will be removed out of the list. however:
- The backend response is that you cant remove a logged in user.
- You cant do any requests anymore in the frontend but you are not redirected to the login page. (sort of limbo state)

2 options:
- Allow logged in users to be deleted in the backend.
- Don't allow logged in users to be deleted in the frontend.

**Comment by sheemeryck** [comment]
I am actually not sure what is exactly happening yet, I can still login with the deleted account, but you lose rights to do certain get requests (I can't see the registered users anymore).

**Comment by Zelzahn** [comment]
I think that the 2nd option ("don't allow logged-in users to be deleted in the frontend") would be the best to implement.

**Comment by Wouter01** [comment]
> I think that the 2nd option ("don't allow logged-in users to be deleted in the frontend") would be the best to implement.

I second that. Also, there is a similar issue with the dropdown for changing roles, since you can't change your own role. Maybe it's best that the dropdown is disabled for the logged in user, too?

**Comment by sheemeryck** [comment]
I think a seperate issue is best for that
