### ISSUE TITLE
Issue with JWT Tokens + Websockets

### ISSUE THREAD

**Issue by Wouter01** [SELab-2/OSOC-5#331]
I encountered a weird bug where a new suggestion was sent 3 times to a client.
So I pushed it to the server in 1 window, and in the other window, it appeared 3 times. I'm not sure what caused this, but I have a feeling this was caused by the refreshtoken.

Why?

When the accesstoken gets invalid, the refreshtoken is sent to make it valid again. If Axios intercepts the issue, it resends the failed request. If I'm right, this leads to the failed request to be sent **3 times** in total (should be checked in network tab).

I'm not sure how websockets work with this situation, so there's not much else I can tell. The suggestion is pushed only once to the server, so the data on the server is correct. When refreshed, the data on the client is corrected to the right amount.

How to reproduce (if my theory is right):

1. Open 2 windows and test the websockets connection.
2. Wait until the accesstoken expires (I think this is after 5 mins)
3. Make a suggestion on one client, check the other client.

For debugging purposes, it may be handy to shorten the valid window of the accesstoken. In issue #208, I explained a way to do this.

**Comment by Zelzahn** [comment]
Do you mean that the BE sends the request thrice to the FE? Or what do you mean with "this leads to the failed request to be sent 3 times"?
