### ISSUE TITLE
Backend does not send url to project

### ISSUE THREAD

**Issue by Wouter01** [SELab-2/OSOC-5#399]
When a project is created, there is a field "project url" that can be filled in. However, this url is not sent by the backend when the project is requested.

**Comment by leveys** [comment]
what do you mean by "project url"? currently a project has the following fields in the backend: `name`, `partner_name`, `extra_info`, `required_skills`, `coaches` and `suggested_students`.

**Comment by Wouter01** [comment]
> what do you mean by "project url"? currently a project has the following fields in the backend: `name`, `partner_name`, `extra_info`, `required_skills`, `coaches` and `suggested_students`.

I'm talking about this:
<img width="1440" alt="Schermafbeelding 2022-05-13 om 18 14 25" src="https://user-images.githubusercontent.com/62355975/168324793-b3e726a1-4aea-43bf-9730-bd990d497c81.png">

However, I'm not sure it's needed. The only thing I could find about it is in this slide:
<img width="1194" alt="afbeelding" src="https://user-images.githubusercontent.com/62355975/168324654-df87a6bc-c43f-4999-92e7-f108eaab7b5e.png">

"Short bio about the partner, **websites**"

**Comment by lisadejonghe** [comment]
I thought that the url of the project resided in `extra_info`

**Comment by leveys** [comment]
we have decided that, sould a url be necessary, it should be included in the `extr_info` field
