### ISSUE TITLE
Mails: Update the search label to make it clear we're searching on name

### ISSUE THREAD

**Issue by Zelzahn** [SELab-2/OSOC-5#424]

**Comment by lisadejonghe** [comment]
I don't think we only filter on name?

**Comment by Zelzahn** [comment]
Yes, what I mean with this issue is that the label here should be updated to reflect that we only filter on name.
![image](https://user-images.githubusercontent.com/2775701/168487771-f5ebd1f6-e157-497f-a2f5-24091aeb9025.png)

**Comment by lisadejonghe** [comment]
It really searches on email too: 
![image](https://user-images.githubusercontent.com/57808740/168651376-29a2dfb6-882e-4449-a32b-de13ca4bb2e1.png)

**Comment by Zelzahn** [comment]
Would a rename to `Search on name and mail` be too verbose?

**Comment by lisadejonghe** [comment]
I think so, that's why I named id `search`
