### ISSUE TITLE
Pagination for skill filter sidebar

### ISSUE THREAD

**Issue by Wouter01** [SELab-2/OSOC-5#436]
There's no pagination for the skill filter in the sidebar. However, I think here it's not really needed and maybe we're better off with just requesting a page_size=500?

@Zelzahn , @lisadejonghe, what are your opinions?

**Comment by Zelzahn** [comment]
In that case I think it would be better to plainly remove the pagination in the BE for skills

**Comment by lisadejonghe** [comment]
Currently, the skills are all fetched in 1 time (page_size=500), which should be more then enough.
