### ISSUE TITLE
Add documentation to Frontend

### ISSUE THREAD

**Issue by Wouter01** [SELab-2/OSOC-5#60]
- [x] components
- [ ] features
     - [x] authentication
     - [ ] mails
     - [ ] projects
     - [x] students
     - [ ] users
 - [ ] stores
     - [x] authenticationStore
     - [x] coachStore
     - [ ] projectStore
     - [ ] skillStore
     - [x] studentStore

**Comment by Zelzahn** [comment]
Ideally, each method and computed property in the Vue files and the stores get some documentation added. This should be a concise explanation of what it does.
